# Data Types
The basic data types in python include types that contain numbers, *text*, **sequences**, and boolean. Many of these data types have *methods* associated with them. Methods are functions associated with certain classes, like data types. Date types often use methods with the syntax
```python
varname.method(<input arguments>)
```
where `method` returns an altered `varname`, but does not always edit the original `varname` directly
## Numeric
Python has three data types for numbers.

In [ ]:
x = 137.
y = 1.618
z = 3+5j
print(type(x))
print(type(y))
print(type(z))
print(x/y)

Notice that Python automatically recognizes the data type for each type of number. There is no need to explicitly specify it.

## Booleans
Booleans are essential for `if`, `for`, and `while` loops. These variables take 1 of two values: True or False.

In [ ]:
int(1>3)

In [ ]:
print((3 == 3) + 2)   # Is five equal 5 to the result of 3 + 2?
int(5 == 6)

In [ ]:
j = "hel"
j + "lo" == "hello"

In [ ]:
x=68
x*9

### Arrays
Arrays are a datatype found in `numpy`; therefore, you must always import `numpy` **before** using them. Arrays in Python are:
1. fixed in size
1. all elements must be of the same type
1. multi-dimensional

The *array* command is stored in the package _numpy_. Arrays can always be used in arithmetic operations, and they store data more efficiently than lists, so when storing lots of data, use arrays.

In [1]:
from numpy import array
a = array([[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30],[31,32,33,34,35]])
print(a)


[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


![python indexing](figures/pythonarray.jpg)

You can slice lists and arrays with a colon **:**

- a[m:n] = subset of *a* starting at index *m* up to but not including *n*
- a[m:n,p:q] = subset of a 2-D array *a* starting in row *m* and column *p* up to but not including row *n* and column *q* 
- a[m:n:step,p:q:step]  = subset of array *a* choosing an element at each step

Omitting numbers before colon means start at the beginning and after the colon means go to end

In [2]:
a[0,1]

np.int64(12)

In [3]:
a[1:3,2:4]

array([[18, 19],
       [23, 24]])

In [4]:
a[::2,::2]

array([[11, 13, 15],
       [21, 23, 25],
       [31, 33, 35]])

### Useful Functions
Some functions in *numpy* help creating and importing arrays. You may also turn lists into arrays.

In [5]:
import numpy as np
A=np.zeros([3,3],int)
B=np.ones([3,3],float)
print(A)
print(B)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
list1 = [3,5,1,3,5,6]
print(list1)

[3, 5, 1, 3, 5, 6]


In [7]:
np.array(list1,float)

array([3., 5., 1., 3., 5., 6.])

Wait a minute! Are you saying I can only get 1D arrays from lists? Well, no. Let's use **lists of lists**

In [8]:
list2 = [[1,4,8],[3,4,9],[-1,4,2]]
print(4*list2)
list2[1][2]

[[1, 4, 8], [3, 4, 9], [-1, 4, 2], [1, 4, 8], [3, 4, 9], [-1, 4, 2], [1, 4, 8], [3, 4, 9], [-1, 4, 2], [1, 4, 8], [3, 4, 9], [-1, 4, 2]]


9

In [9]:
newarray = np.array(list2)
print(3*newarray)

[[ 3 12 24]
 [ 9 12 27]
 [-3 12  6]]


You can load data from files **fairly** easily with *loadtxt*. Documentation on *dtype* and the notation used below is available at https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dtype.html

In [12]:
test=np.loadtxt("data/globaltemps.txt", dtype={'names': ('year','temp'),
...                      'formats': ('i4', 'f4')})
print(test)

FileNotFoundError: data/globaltemps.txt not found.

In [11]:
id=test['temp']>0.5
print(id)
tp=test['year'][id]
print(tp)

NameError: name 'test' is not defined

In [13]:
test['temp']

NameError: name 'test' is not defined

In [14]:
t = test.tolist()
print(test.tolist()) # convert array to list
print(t)

NameError: name 'test' is not defined

## Sequences
Sequences in Python include `lists`, `tuples` (`ranges`), and `strings`. Lists are a simple way of storing related data, much like arrays or tables in MATLAB. Tuples act much like lists, but are immutable, meaning once created they *cannot* be modified. Ranges refer to the built-in function `range` (and its many similar cousins: `arange`, `xrange`, etc). `range` is used to create a range of values. `strings` allow for text to be stored and manipulated.
### Lists

In [21]:
list1=['photon', 'W+ boson', 'W- boson', 'Z boson', 'gluon', 'graviton'];

In [22]:
list1.pop()
print(notreal)

NameError: name 'notreal' is not defined

In [23]:
list1

['photon', 'W+ boson', 'W- boson', 'Z boson', 'gluon']

In [24]:
x = list1.append(notreal)
print(x)
print(list1)

NameError: name 'notreal' is not defined

In [25]:
print(list1[0:4])
'photon' in list1

['photon', 'W+ boson', 'W- boson', 'Z boson']


True

### Tuples

In [26]:
tuple1 = ('photon', 'W+ boson', 'W- boson', 'Z boson', 'gluon', 'graviton')

In [27]:
tuple1[3:5]

('Z boson', 'gluon')

In [28]:
tuple1[6]='gamma'

TypeError: 'tuple' object does not support item assignment

In [29]:
(em,weak1,weak2,weak3,strong,gravity)=tuple1
print(weak2)
print(strong)

W- boson
gluon


you often need to switch the values of two variables, tuples gives you an easy way:

In [30]:
a='switch'
b=3.1415
(a,b)=(b,a)
print(a)
print(b)

3.1415
switch


In [31]:
for k in tuple1:
    print(k)

photon
W+ boson
W- boson
Z boson
gluon
graviton


`range` is a type much like a `tuple` in that you specify the values at its creation and cannot/should not be altered after creation.

In [32]:
r1=range(6)
r2=range(1,19)
r3=range(1,44,4)
print(r1)
print(r2)
print(r3[3])
print(type(r3))

range(0, 6)
range(1, 19)
13
<class 'range'>


### Strings
str is the only data type used to contain text in Python

In [33]:
text1 = "There is no difference between characters and strings. "
text2 = 'Single or double quotes give you the same thing'
print(type(text1))
print(type(text2))
print(text1[9])
print(text2[0:6])
print(text1*2)

<class 'str'>
<class 'str'>
n
Single
There is no difference between characters and strings. There is no difference between characters and strings. 


`str` is quite the flexible data type in Python. Below are some examples of ways to use strings. Many more methods can be found at [string methods](https://www.programiz.com/python-programming/methods/string/join)

In [34]:
gettysburg = "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal. Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper that we should do this. But, in a larger sense, we can not dedicate -- we can not consecrate -- we can not hallow -- this ground. The brave men, living and dead, who struggled here, have consecrated it, far above our poor power to add or detract. The world will little note, nor long remember what we say here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here have thus far so nobly advanced. It is rather for us to be here dedicated to the great task remaining before us -- that from these honored dead we take increased devotion to that cause for which they gave the last full measure of devotion -- that we here highly resolve that these dead shall not have died in vain -- that this nation, under God, shall have a new birth of freedom -- and that government of the people, by the people, for the people, shall not perish from the earth."
substr= " we "
print(gettysburg.count(substr)) # count 'we's in the address
print(gettysburg.casefold().count(substr)) # counts we's regardless of capitalization
print(gettysburg.find(substr))
print(gettysburg[181:183])
gettysburg.replace("Four ","NOPE ")
print(gettysburg)

8
10
180
we
Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal. Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper that we should do this. But, in a larger sense, we can not dedicate -- we can not consecrate -- we can not hallow -- this ground. The brave men, living and dead, who struggled here, have consecrated it, far above our poor power to add or detract. The world will little note, nor long remember what we say here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here

## Dictionaries
The basic data container in Python is a list. A `list` can hold a variety of data types. Once a `list` exists, it can be appended, have elements deleted, and be transformed into `arrays` or `tuples`. Of course, there are more sophisicated ways of storing/accessing/processing data in Python. Let's look at two: `dictionaries` and `dataframes`. Content below is generously sampled from http://openbookproject.net/thinkcs/python/english3e/dictionaries.html.
Dictionaries are lists of values that are indexed by `keys`. In other languages, these dictionaries are often referred to associative arrays because it is a way to associate `keys` with values. Examples of using dictionaries:
* English to Spainish dictionary

In [ ]:
entosp = {"one":"uno","two":"dos","three":"tres"} # `key:value` elements
entosp["one"]

* Inventory of supplies

In [ ]:
office = {"highlighters":200,"pencils":300,"pens":500}
office['pens']

You could construct a dictionary for a encryption code:

In [ ]:
codex = { "a": 1, "b": 2, "c": 3, "d": 4, "e": 5, "f": 6, "g": 7, "h": 8, "i": 9, "j": 10,"k": 11,"l": 12,"m": 13,"n": 14,
         "o": 15,"p": 16,"q": 17,"r": 18,"s": 19,"t": 20,"u": 21,"v": 22,"w": 23,"x": 24,"y": 25}
print(codex)
print(codex["g"])

You can add new keys after the initial definiton:

In [ ]:
codex["z"]=26
print(codex)

You can update the values in the dictionary

In [ ]:
office["pens"]+=200
print(office)

You can find out how many `key:values` pairs a dictionary has

In [ ]:
len(codex)

### Dictionary Methods
Dictionaries are a type of class in Python, and classes have functions associated with them called `methods`. Methods allow you to perform operations on and with the dictionary. 
You can always get the keys and the values from any dictionary, using the methods `keys` and `values`

In [ ]:
print(office.values())
print(office.keys())
print(list(office.values()))

You can run over all the keys to process the values or run through the values explicitly.

In [ ]:
print("Let's count in Spanish")
for k in entosp.keys():   # The order of the k's is not defined
   print(entosp[k])


In [ ]:
print("Let's look at the code")
for k in codex:   # The order of the k's is defined
   print(k,"oops") # 

The method `items` can be used to iterate over the keys and values or to grab both the keys and the values.

In [ ]:
list(office.items())

In [ ]:
for (k,v) in codex.items():
    print(k, "=", v)

## Sets
Sets are much like `tuples`. A `set` is a collection which is unordered and unindexed. In Python, sets are written with curly brackets. Once sets are created, they may not be changed or accessed directly, but you may run through them in a `for` statement. A set is useful because Python has methods that allow you to perform set theory operations on this datatype.

In [ ]:
thisset = {"apple", "banana", "cherry"}
print(thisset)

In [ ]:
thisset = {"apple", "banana", "cherry"}
for x in thisset:
  print(x)

In [ ]:
thisset = {"apple", "banana", "cherry"}
print("banana" in thisset)

In [ ]:
thisset = {"apple", "banana", "cherry"}
thisset.add("orange")
#thisset.append("kiwi")
print(thisset)

In [ ]:
thisset2 = {"apple", "banana", "cherry"}
thisset2.update({"orange", "mango", "grapes"})
print(thisset2)

Let's try some of the set operations like intersection, difference, and union

In [ ]:
thisset.intersection(thisset2)

In [ ]:
thisset.difference(thisset2)

In [ ]:
thisset.union(thisset2)

In [ ]:
thisset[1]